# Generated by Django 5.1.5 on 2025-01-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now_add=True)),
                ('status_attempt', models.CharField(choices=[('successfully', 'Успешно'), ('unsuccessful', 'Неуспешно')], default='unsuccessful', max_length=15)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['status_attempt'],
            },
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема письма')),
                ('message_body', models.TextField(blank=True, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рассылки')),
                ('start_sending', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала рассылки')),
                ('end_sending', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='created', max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.message')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status'],
                'permissions': [('can_canceled_sending', 'Can canceled sending')],
            },
        ),
    ]
