# Generated by Django 5.1.5 on 2025-01-19 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите владельца рассылки', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='sending',
            name='recipient',
            field=models.ManyToManyField(to='mailing.mailingrecipient'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.sending'),
        ),
    ]
