# Generated by Django 5.1.5 on 2025-01-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
