# Generated by Django 5.1.5 on 2025-01-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_sending_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='name',
        ),
    ]
